spring:
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/codehub
    username: madjo
    password: Qq123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
db:
  schema: public