spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/codehubtest
    username: madjo
    password: Qq123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
db:
  schema: public